name: Update README with Project Links

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # Monthly on the 1st

permissions:
  contents: write

env:
  TOP_N: 5  # Number of newest repos to display

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Skip if last commit < 24h ago
      - name: Check last commit time
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          if [ $TIME_DIFF -lt 86400 ]; then
            echo "Last commit less than 24 hours ago. Skipping update."
            exit 0
          fi

      # Step 3: Extract existing project lines
      - name: Extract existing project links
        run: |
          awk '/^## Projects/{flag=1; next} /^## /{flag=0} flag' README.md > existing_projects.md || true

      # Step 4: Fetch top N newest repos excluding the current repo
      - name: Fetch top N newest repos
        run: |
          FULL_REPO="${{ github.repository }}"
          REPO_NAME="${FULL_REPO#*/}"
          echo "Excluding current repo: $REPO_NAME"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos?type=public&per_page=100&sort=updated" \
          | jq -r --arg repo "$REPO_NAME" --argjson n $TOP_N \
            'map(select(.fork == false and .name != $repo)) | sort_by(.updated_at) | reverse | .[:$n][] | "- [\(.name)](\(.html_url))"' > fetched_projects.md

          echo "Fetched top $TOP_N projects:"
          cat fetched_projects.md

      # Step 5: Match only top N URLs to existing custom names
      - name: Build final project list strictly from top N
        run: |
          # Extract URLs of the top N repos
          awk '{ match($0, /\((https:\/\/github\.com\/[^)]+)\)/, a); if(a[1]!="") print a[1] }' fetched_projects.md > fetched_urls.txt

          # Filter existing projects ONLY for those URLs
          grep -Ff fetched_urls.txt existing_projects.md > preferred_existing_filtered.md || true

          # Create a mapping: url -> custom line
          awk '{
            match($0, /\((https:\/\/github\.com\/[^)]+)\)/, arr)
            if(arr[1]!="") map[arr[1]]=$0
          } END {
            for(k in map) print k "\t" map[k]
          }' preferred_existing_filtered.md > custom_map.txt

          # Now build the final list: For each fetched repo (top N),
          # check if it has a custom name, else use default
          > final_list.md
          while IFS= read -r line; do
            if [[ "$line" =~ \(https:\/\/github\.com\/[^)]+\) ]]; then
              url=$(echo "$line" | grep -o '(https[^)]*)' | tr -d '()')
              custom=$(grep -F "$url" custom_map.txt | cut -f2-)
              if [ -n "$custom" ]; then
                echo "$custom" >> final_list.md
              else
                echo "$line" >> final_list.md
              fi
            fi
          done < fetched_projects.md

          # Sort alphabetically by display text (case-insensitive)
          sort -f final_list.md > sorted_projects.md

          echo "Final strictly top N project list:"
          cat sorted_projects.md

          # Replace README section
          awk '
            BEGIN { in_projects=0 }
            /^## Projects/ {
              print
              print ""  # blank line after header
              while ((getline line < "sorted_projects.md") > 0) print line
              close("sorted_projects.md")
              print ""  # blank line before next section
              in_projects=1
              next
            }
            in_projects && /^## / { in_projects=0 }
            !in_projects
          ' README.md > README.tmp

          mv README.tmp README.md

      # Step 6: Commit changes if any
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with top $TOP_N newest project links" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin main

      # Step 7: Cleanup
      - name: Clean up temporary files
        run: rm -f *.md *.txt
