name: Update README with Project Links

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # Monthly on the 1st

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Skip if last commit was < 24 hours ago
      - name: Check last commit time
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          if [ $TIME_DIFF -lt 86400 ]; then
            echo "Last commit was less than 24 hours ago. Skipping update."
            exit 0
          fi

      # Step 3: Extract 'Projects' section from README
      - name: Extract existing project links
        run: |
          awk '/^## Projects/{flag=1; next} /^## /{flag=0} flag' README.md > existing_projects.md || true

      # Step 4: Fetch all public repos
      - name: Fetch list of public repos from GitHub
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos?type=public&per_page=100" \
          | jq -r '.[] | select(.fork==false and .name != "Kentthou") | "- [\(.name)](\(.html_url))"' > fetched_projects.md

      # Step 5: Merge, deduplicate by URL, prefer existing names, sort alphabetically
      - name: Merge and sort project links cleanly
        run: |
          # Create a map of URL -> preferred line (prefer existing display names)
          awk -F'[()]' '/^- \[.*\]\(.*\)/ { url=$2; line=$0; existing[url]=line } END { for (k in existing) print existing[k] }' existing_projects.md > preferred_existing.md

          # Combine existing preferred + fetched ones
          cat preferred_existing.md fetched_projects.md | grep -v '^\s*$' > merged_all.md

          # Deduplicate by URL (keep first occurrence = existing preferred)
          awk -F'[()]' '!seen[$2]++' merged_all.md > deduped.md

          # Sort alphabetically by display text (case-insensitive)
          sort -f deduped.md > sorted_projects.md

          # Rewrite README with sorted list + preserve blank line before next header
          awk '
            BEGIN { in_projects=0 }
            /^## Projects/ {
              print
              print ""    # always keep a blank line after Projects header
              while ((getline line < "sorted_projects.md") > 0) print line
              close("sorted_projects.md")
              print ""    # add a blank line before next section
              in_projects=1
              next
            }
            in_projects && /^## / { in_projects=0 }
            !in_projects
          ' README.md > README.tmp

          mv README.tmp README.md

      # Step 6: Commit and push if README changed
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Alphabetically update and deduplicate project links in README" || echo "No changes to commit"
          git push

      # Step 7: Clean up temp files
      - name: Clean up temporary files
        run: rm -f *.md *.txt
