name: Update README with Project Links

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository so we can read and write files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Skip the job if the last commit was less than 24 hours ago
      - name: Check last commit time
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          if [ $TIME_DIFF -lt 86400 ]; then
            echo "Last commit was less than 24 hours ago. Skipping update."
            exit 0
          fi

      # Step 3: Extract current list of project links from the README
      - name: Extract existing project links
        run: |
          awk '/^## Projects/{flag=1; next} /^## /{flag=0} flag' README.md > existing_projects.md

      # Step 4: Fetch the full list of public repositories
      - name: Fetch list of public repos from GitHub
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos?type=public&per_page=100" \
          | jq -r 'sort_by(.name) | .[] | select(.fork==false and .name != "Kentthou") | "- [\(.name)](\(.html_url))"' > all_projects.md

      # Step 5: Compare new project list against existing ones
      - name: Find new projects not in README
        run: |
          grep -Fxv -f existing_projects.md all_projects.md > new_projects.md || true

      # Step 6: Append new project links at the end of the Projects section
      - name: Append new projects to README
        run: |
          if [ -s new_projects.md ]; then
            awk '
              /^## Projects/ {
                print
                in_projects = 1
                next
              }
              in_projects && /^## / {
                in_projects = 0
              }
              { print }
            ' README.md > README.tmp

            echo "" >> README.tmp
            cat new_projects.md >> README.tmp

            mv README.tmp README.md
          else
            echo "No new projects to add."
          fi

      # Step 7: Commit and push changes if any were made
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update project links in README" || echo "No changes to commit"
          git push
