name: Update README with Project Links

on:
  push:
  schedule:
    - cron: '0 0 1 * *' # Runs on first day of the month Midnight UTC

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check last commit time
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          if [ $TIME_DIFF -lt 86400 ]; then
            echo "Last commit was less than 24 hours ago. Skipping update."
            exit 0
          fi

      - name: Fetch project list
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos?type=public&per_page=100" \
          | jq -r 'sort_by(.name) | .[] | select(.fork==false and .name != "Kentthou") | "- [\(.name)](\(.html_url))"' > new_projects.md

      - name: Replace Projects section in README
        run: |
          awk '
            BEGIN { in_projects = 0 }
            /^## Projects/ {
              print
              print ""
              while ((getline line < "new_projects.md") > 0) print line
              in_projects = 1
              next
            }
            in_projects && /^## / { in_projects = 0 }
            !in_projects || /^## / { print }
          ' README.md > README.new && mv README.new README.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update project links in README" || echo "No changes to commit"
          git push
